<div class='info'>Inviwo (v0.9.12-pre) Log File</div>
<div class='info nowrap'>Created at: 2025-09-26 15:23:35 </div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo::InviwoApplication::printApplicationInfo:267) Inviwo Version: 0.9.12-pre</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo::InviwoApplication::printApplicationInfo:274) Base Path: /Users/jenkins/actions-runner/_work/inviwo/inviwo/inviwo</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo::InviwoApplication::printApplicationInfo:275) ThreadPool Worker Threads: 6</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo::InviwoApplication::printApplicationInfo:277) Config: Ninja [RelWithDebInfo] AppleClang (16.0.0.16000026)</div>
<div class='info nowrap'><span class='level'>Info: </span>(main:98) Qt Version 6.9.1</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo::CImgModule::CImgModule:71) Using LibJPG Version 62</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo::CImgModule::CImgModule:72) Using OpenEXR Version 3.3.5</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo:::314) Python runtime version: 3.12.9 (main, Sep 23 2025, 15:24:39) [Clang 16.0.0 (clang-1600.0.26.4)], build version 3.12.9</div>
<div class='info nowrap'><span class='level'>Info: </span>(inviwo:::353) Internal python found</div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;built-in function __import__&gt; returned a result with an exception set</div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) Internal error: pybind11::error_already_set called while Python error indicator not set.</div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) Object of type &apos;numpy.dtypes.VoidDType&apos; is not an instance of &apos;dtype&apos;</div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) Object of type &apos;numpy.dtypes.VoidDType&apos; is not an instance of &apos;dtype&apos;</div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) Object of type &apos;numpy.dtypes.VoidDType&apos; is not an instance of &apos;dtype&apos;</div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
<div class='error nowrap'><span class='level'>Error: </span>(inviwo:::255) SystemError: &lt;class &apos;numpy._core._internal._Stream&apos;&gt; returned a result with an exception set<br/><br/>At:<br/>  /Users/jenkins/actions-runner/_work/inviwo/inviwo/build/vcpkg_installed/x64-osx-dynamic/lib/python3.12/site-packages/numpy/_core/_internal.py(668): _dtype_from_pep3118<br/>  &lt;frozen importlib._bootstrap&gt;(488): _call_with_frames_removed<br/>  &lt;frozen importlib._bootstrap_external&gt;(1301): exec_module<br/>  &lt;frozen importlib._bootstrap&gt;(935): _load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1331): _find_and_load_unlocked<br/>  &lt;frozen importlib._bootstrap&gt;(1360): _find_and_load<br/>  &lt;string&gt;(25): &lt;module&gt;<br/></div>
